// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "___VARIABLE_productName___",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "___VARIABLE_productName___",
            targets: ["AppModule"],
            bundleIdentifier: "___VARIABLE_bundleIdentifierPrefix:bundleIdentifier___.___VARIABLE_productName:RFC1034Identifier___",
            teamIdentifier: "___DEVELOPMENTTEAMIDENTIFIER___",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: ___PLACEHOLDERICON___,
            accentColor: ___ACCENTCOLOR___,
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
