//___FILEHEADER___
//___COREDATAFILECOMMENTEPILOGUE___

import Foundation
import CoreData

___OBJCATTRIBUTE___
public class ___COREDATA_MANAGEDOBJECT_CLASS___: ___COREDATAMANAGEDOBJECTSUPERCLASS___ {

}
